name: Build and Push

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Free disk space
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: true
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          docker-images: true
          swap-storage: true

      - name: Login to registry
        uses: docker/login-action@v3
        with:
          registry: registry.ai.in.th
          username: nontapat.jf0n
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./textsum
          push: true
          tags: registry.ai.in.th/2026-textsum/47b13a1c/nontapat.jf0n:v15
